config/routes.rb
Rails.application.routes.draw do
  root "tarefas#index"

  resources :tarefas, except: %i[ show ] do
    collection do
      get :export_csv
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tarefa.rb
class Tarefa < ApplicationRecord
  validates :description, presence: true
  validates :done, inclusion: { in: [true, false] }

  belongs_to :parent, class_name: "Tarefa", optional: true
  has_many :sub_tarefas, class_name: "Tarefa", foreign_key: :parent_id, dependent: :destroy

  scope :only_parents, -> { where(parent_id: nil) }

  def symbol
    case status
    when "pending" then "»"
    when "done" then "✓"
    when "expired" then "x"
    end
  end

  def css_color
    case status
    when "pending" then "primary"
    when "done" then "success"
    when "expired" then "danger"
    end
  end

  def parent?
    parent_id.nil?
  end

  def sub_tarefas?
    !parent?
  end

  private

  def status
    return "done" if done?

    due_date.past? ? "expired" : "pending"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate

  private

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == Rails.application.credentials.authentication[:username] &&
      password == Rails.application.credentials.authentication[:password]
    end
  end
end

app/controllers/concerns/exportable.rb
require "csv"

module Exportable
  extend ActiveSupport::Concern

  def export_csv
    headers = ["ID", "Descrição", "Finalizada", "ID da tarefa pai", "Criada em", "Atualizada em"]

    csv = CSV.generate(write_headers: true, headers: headers) do |row|
      Tarefa.all.each do |tarefa|
        row << [
          tarefa.id,
          tarefa.description,
          tarefa.done? ? "Sim" : "Não",
          tarefa.parent_id,
          I18n.l(tarefa.created_at, format: "%d/%m/%Y, %Hh%M"),
          I18n.l(tarefa.updated_at, format: "%d/%m%Y, %Hh%M"),
        ]
      end
    end

    send_data csv, type: "text/csv; charset=utf8; header=present",
                   disposition: "attachment; filename=tarefa.csv"
  end
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  include Exportable

  before_action :set_tarefa, only: %i[ edit update destroy ]

  # GET /tarefas or /tarefas.json
  def index
    @tarefas = Tarefa.only_parents.order(:due_date)
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new
  end

  # GET /tarefas/1/edit
  def edit
  end

  # POST /tarefas or /tarefas.json
  def create
    @tarefa = Tarefa.new(tarefa_params)

    if @tarefa.save
      redirect_to tarefas_path, notice: "Tarefa foi criada com sucesso."
    else
      flash.now[:alert] = @tarefa.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tarefas/1 or /tarefas/1.json
  def update
    if @tarefa.update(tarefa_params)
      redirect_to tarefas_path, notice: "Tarefa foi atualizada com sucesso."
    else
      flash.now[:alert] = @tarefa.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tarefas/1 or /tarefas/1.json
  def destroy
    @tarefa.destroy

    redirect_to tarefas_url, notice: "Tarefa deletada com sucesso."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tarefa
    @tarefa = Tarefa.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tarefa_params
    params.require(:tarefa).permit(:description, :due_date, :done, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", media: 'all' %>
    <%= javascript_pack_tag "application" %>

  </head>

  <body>

    <div class='d-flex h-100 align-items-center justify-content-center row bg-gradient-primary'>
      <main class='col-11 col-md-10 col-lg-8 shadow-lg p-5 mb-5 bg-white rounded'>
        <% flash.each do |type, message| %>
        <div class="alert alert-<%= type == 'alert' ? 'danger' : 'success' %> alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <% end %>

        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/tarefas/_form.html.erb
<%= form_with(model: tarefa, local: true) do |form| %>
  <%= form.hidden_field :parent_id, value: tarefa.parent_id || params[:parent_id] %>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :done, class: 'form-check-input' %>
    <%= form.label :done, class: 'form-check-label' %>
  </div>

  <%= form.submit class: 'btn btn-primary', data: { disable_with: 'Salvando...' } %>

  <%= link_to 'Cancelar', tarefas_path, class: 'btn btn-light' %>
<% end %>

app/views/tarefas/_table_row.html.erb
<tr class='<%= tarefa.parent? ? 'border-top' : '' %>'>
  <td class="<%= tarefa.sub_tarefas? ? 'ps-5' : '' %>">
    <span class="text-<%= tarefa.css_color %> pe-1"> <%= tarefa.symbol %> </span>

    <% if tarefa.done? %>
      <s class="text-muted"><%= tarefa.description %></s>
    <% else %> 
      <%= tarefa.description %> 
    <% end %>
  </td>

  <td><%= l tarefa.due_date if tarefa.due_date %></td>

  <td class="text-right" style="padding-right: 0px;">
    <%= link_to 'Editar', edit_tarefa_path(tarefa), class: 'btn btn-secondary btn-sm' %> 
    <%= link_to 'Apagar', tarefa, method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Tem certeza?' } %>
    
    <% if tarefa.parent? %>
      <%= link_to '+ Sub-tarefa', new_tarefa_path(parent_id: tarefa.id), class: 'btn btn-success btn-sm' %> 
    <% end %>
  </td>
</tr>

app/views/tarefas/_tarefa.html.erb
<div id="<%= dom_id tarefa %>">
  
</div>

app/views/tarefas/edit.html.erb
<h1 class="display-4">
    Editar <%= @tarefa.parent? ? 'tarefa' : 'sub_tarefa' %>
</h1>
  
<%= render "form", tarefa: @tarefa %>

app/views/tarefas/index.html.erb
<div class="row mb-2">
  <div class="col-8">
    <h1 class="display-4">Tarefas</h1>
  </div>

  <div class="col-4 mt-4 text-right">
    <%= link_to "+ Tarefa", new_tarefa_path, class: 'btn btn-success' %>
    <%= link_to "Exportar CSV", export_csv_tarefas_path, class: 'btn btn-info' %>
  </div>
</div>

<% if @tarefas.any? %>
  <table class="table table-borderless">
    <thead>
      <tr>
        <th>Descrição</th>
        <th>Prazo</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tarefas.each do |tarefa| %>
        <%= render 'table_row', tarefa: tarefa %>

        <% tarefa.sub_tarefas.order(:due_date).each do |sub_tarefa| %>
          <%= render 'table_row', tarefa: sub_tarefa %>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Nenhuma tarefa foi cadastrada ainda.</p>
<% end %>

app/views/tarefas/new.html.erb
<h1 class="display-4">
    Nova <%= params[:parent_id].present? ? 'sub_tarefa' : 'tarefa' %>
</h1>
  
<%= render "form", tarefa: @tarefa %>